# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Started', models.TimeField()),
                ('Success', models.IntegerField()),
                ('Experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Type', models.IntegerField(choices=[(0, 'Float'), (1, 'Integer'), (2, 'Boolean'), (3, 'String'), (4, 'File')])),
                ('ExperimentSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.ExperimentSet')),
            ],
        ),
        migrations.CreateModel(
            name='MetricFloatValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricIntegerValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricStringValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ExperimentRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.ExperimentRun')),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Started', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricBooleanValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.BooleanField()),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.MetricValue')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricFileValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.MetricValue')),
            ],
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='Run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.Run'),
        ),
        migrations.AddField(
            model_name='metricstringvalue',
            name='Metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.MetricValue'),
        ),
        migrations.AddField(
            model_name='metricintegervalue',
            name='Metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.MetricValue'),
        ),
        migrations.AddField(
            model_name='metricfloatvalue',
            name='Metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.MetricValue'),
        ),
        migrations.AddField(
            model_name='experimentrun',
            name='Run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.Run'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='ExperimentSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyxperiment_ui.ExperimentSet'),
        ),
    ]
