# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Started', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseMetricValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TestCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetric',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Type', models.IntegerField(choices=[(0, 'Double'), (1, 'Integer'), (2, 'Boolean'), (3, 'String'), (4, 'File')])),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricBooleanValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.BooleanField()),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCaseMetricValue')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricDoubleValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.FloatField()),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCaseMetricValue')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricFileValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCaseMetricValue')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricIntegerValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.IntegerField()),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCaseMetricValue')),
            ],
        ),
        migrations.CreateModel(
            name='TestMetricStringValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Value', models.CharField(max_length=256)),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCaseMetricValue')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Started', models.TimeField()),
                ('Success', models.IntegerField()),
                ('Run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.Run')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='testcasemetricvalue',
            name='TestMetric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestMetric'),
        ),
        migrations.AddField(
            model_name='testcasemetricvalue',
            name='TestRun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeasureTestWebUI.TestRun'),
        ),
    ]
